global using System;
global using System.Net;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Logging;
global using Infrastructure.Services.Interfaces;
global using Infrastructure.Services;
global using Infrastructure;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Options;