global using System;
global using System.Threading.Tasks;
global using FluentAssertions;
global using Infrastructure.Services.Interfaces;
global using Microsoft.Extensions.Logging;
global using Moq;
global using Xunit;
global using Microsoft.Extensions.Options;
global using StackExchange.Redis;
